project_name: {{cookiecutter.project_name}}

input_data:
  raw_dir: "data/raw/"
  processed_dir: "data/processed/"

outputs:
  outputs_dir: "outputs/"
  logs_dir: "outputs/logs/"

credentials:
  aws: "~/.aws"
  other: "~/.credentials"
